import { Router } from "express";
import multer from "multer";
import { requireAdmin } from "../middleware/requireAdmin";
import { adminLogin, bulkUploadQuestions, createCombination, createExam, deleteExam, deleteQuestionBatch, deleteUnbatchedQuestions, listAdminData, listQuestionBatches, overallScoreboard, publishOverallScoreboard, publishScoreboard, scoreboard, toggleExam } from "../controllers/adminController";

const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
router.post("/login", adminLogin);
router.use(requireAdmin);
router.get("/data", listAdminData);
router.get("/scoreboard/overall", overallScoreboard);
router.post("/subject-combinations", createCombination);
router.post("/questions/bulk-upload", upload.single("file"), bulkUploadQuestions);
router.get("/question-batches", listQuestionBatches);
router.delete("/questions/unbatched", deleteUnbatchedQuestions);
router.delete("/question-batches/:batchId", deleteQuestionBatch);
router.post("/exams", createExam);
router.patch("/exams/:id", toggleExam);
router.delete("/exams/:id", deleteExam);
router.get("/scoreboard/:examId", scoreboard);
router.patch("/scoreboard/overall/publish", publishOverallScoreboard);
router.patch("/scoreboard/:examId/publish", publishScoreboard);
export default router;